language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: IFOUFpwU+gIPj372aubnwyGI2nQqVF0H6BQRqk1WDtY0MiDNvZiLBEmuUZlQllYNAP1RXqyCfl76oR2YzP7mewOgrnqgEJF7lAOKb3sqZoeFpZpc3OmYC5nzhKe91w6+bWQLBnagfvQcCcfflgjIUvNfKPQMQI5FyNgEnw5Y/uL08dgPeQ5JW9eCChF0RoG7TP7+Z0B1r1AS9uTdtDv7zkq1x0YRfu/qQI1u1FYtLvVfjs/TIG3HMd1GCjOzE7jUZl8fe1zA6s7OCPPTIJB70rAotOX3wmu3KZrJDzXlBqgzdSrpQsH784M70KzPJMuM7TXBcQ4kEcox1yQB+JSdUJ+TqOSxUavT9Rxt+hi1PzGgnoxmYN4EAfgNYOALPZVzGIIfZduuq770sV+TkxyQ4Mow11IbegoMxgUCho5c2GO0+ba/x2/8MuoWSPmj50DulQ2/WYG+BnMUnjgmQVDu99YXmwChPtYrSILNwMwoTrTr5KAYxBjw4Y4baM9QmjyayQH6gf4QAGtM3a2WWPm8MfqbnboT5vynxTcealvTwNSF8yVqpd4rKjw3Jo7CZ0M7CpY2VYGF5IxmmWT86zeu9l+SZA/btxDxOd8euTs1UbRqMU68mggkvf4jQxSM7t+43eUV3UARPlxSwnoHJY4/3GWjqt/k0mIYhCKYLqTHq2E=
  on:
    repo: ajaxscape/tamarin-dom-sleuth
    branch: master
