language: node_js
node_js:
- '6'
script:
- sh scripts/coverage.sh
deploy:
  provider: npm
  email: ben@ajaxscape.com
  api_key:
    secure: Ncs6Iez751teDwSmDo6dWn41w+z1UHa6qsJeur2nAOqJykq66rE1y21cP0seLS1c4mCgc/54TTY8g4VNSYmVu/A/wFEPbzbhk5LTpaZUsop4LSe8BIhQan/0NLrirIp/JeVeYgG+lR+Pl+vF3Ze3e4XGtxmGBncQ8ksdKRhwJpMQoWo2j/3wGoPajlUzuTRvJOoSUgTe/o7ysCx2R3RO3J/CBpyvKMfFEC8AEQa5iAZ12NlfZQyeHve1Jr3eDFbwT8FKUGl8Z9ZoDgqhTzJ1FddsXhp3gZASBGqzbF6dW+OI1YNbBpon7H/KfA8TsAGuFNBjhzaPoPGqPaBRBRZIgEOopdCyQA3nxoCVgMXO5uoI66nXXFiHzo+jtYKYzhO0V8efhEjaepekJIzBJj6EdtQwiGNHEwuebP3fVUkmvMZ44Rmr3/1Yw4pelAlo5Sl55f2xgKfcL9CID57EMFkBZAAX9fU/XtlwMMrIuX1LkQ3xTGD/7pF58Agu0Po6ZduHuPlAk75+FDwrmvYsTAX+mCBPm/+bLnEHPUVymrRyQIWKzXiKKzj1Y9RfumBQkGK1fi7nbdslRhzpXxloW90ftipqM/pojUsQ9oivCwfyYvsgJBZzgHVfCY30pvulkBa6s7WZGwWXnoJ1TPreOxFea6h4Jifx2MQlBUDukg/mX7k=
  on:
    repo: ajaxscape/tamarin-dom-sleuth
    branch: master
